banner-active = true
banner = "**RSVP NOW: Our panel of experts answer your questions on the COVID-19 resurgence »**"
banner-link = "https://inquirer.zoom.us/webinar/register/WN_s2yh3_s8TOqQ3J8UkgqGew"
banner-bg-color = "#c200ff"
banner-text-color = "#000000"
promo-active = true
promo-type = "image"
promo-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01gh/kdt1/aug-flash-challenge-banner.png"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01gh/kdsp/aug-flash-challenge-mobile.png"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
show-newsletter = true
show-sticky = true
sticky-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
sticky-image = "https://files.data.spotlightpa.org/uploads/01gh/kdsp/aug-flash-campaign-square.png"
sticky-link = "/donate/"