banner-active = true
banner = "**LIVE CORONAVIRUS TRACKER:** The latest county-by-county cases, hospitalizations, and more"
banner-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
promo-type = "image"
promo-image-caption = "Donate to Spotlight PA"
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01fs/ds6e/strengthen-banner.svg,https://files.data.spotlightpa.org/uploads/01fs/ds68/strengthen-banner-black.svg"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01fv/8bc5/community-rectangle-doubled.svg,https://files.data.spotlightpa.org/uploads/01fv/8bc9/democracy-rectangle-doubled.svg,https://files.data.spotlightpa.org/uploads/01fv/8bcq/environment-rectangle-doubled.svg,https://files.data.spotlightpa.org/uploads/01fv/8bcx/environment-rectangle-doubled.svg,https://files.data.spotlightpa.org/uploads/01fv/8bd3/future-rectange-doubled.svg,https://files.data.spotlightpa.org/uploads/01fv/8bda/health-rectangle-doubled.svg"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
show-newsletter = true
show-sticky = true
sticky-image-caption = "Donate to Spotlight PA"
sticky-image = "https://files.data.spotlightpa.org/uploads/01fv/8bch/double-square.svg,https://files.data.spotlightpa.org/uploads/01fv/8bdf/strengthen-black-square.svg,https://files.data.spotlightpa.org/uploads/01fv/8bdn/works-for-you-square.svg"
sticky-link = "/donate/"