banner-active = true
banner = "**THE URGENCY OF NOW: Support fact-based journalism that holds the powerful to account »**"
banner-link = "/donate/"
banner-bg-color = "#ea5b3a"
banner-text-color = "#ffffff"
promo-active = true
promo-type = "image"
promo-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01gj/dbnw/13.png, https://files.data.spotlightpa.org/uploads/01gj/dbnw/14.png, https://files.data.spotlightpa.org/uploads/01gj/dbnw/15.png, https://files.data.spotlightpa.org/uploads/01gj/dbnw/16.png, https://files.data.spotlightpa.org/uploads/01gj/dbnx/17.png"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01gj/dbjm/8.png, https://files.data.spotlightpa.org/uploads/01gj/dbjn/9.png, https://files.data.spotlightpa.org/uploads/01gj/dbjn/10.png, https://files.data.spotlightpa.org/uploads/01gj/dbjn/11.png, https://files.data.spotlightpa.org/uploads/01gj/dbjn/12.png"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
show-newsletter = true
show-sticky = true
sticky-image-caption = "Spotlight PA's vital investigative journalism depends on your support. It's that simple. Contribute now."
sticky-image = "https://files.data.spotlightpa.org/uploads/01gj/dbrp/13.png, https://files.data.spotlightpa.org/uploads/01gj/dbrn/12.png, https://files.data.spotlightpa.org/uploads/01gj/dbrn/11.png, https://files.data.spotlightpa.org/uploads/01gj/dbrn/10.png, https://files.data.spotlightpa.org/uploads/01gj/dbrm/9.png"
sticky-link = "/donate/"