banner-active = true
banner = "**LIVE CORONAVIRUS TRACKER:** The latest county-by-county cases, hospitalizations, and more"
banner-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
promo-type = "image"
promo-image-caption = "Donate to Spotlight PA"
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01fs/ds6e/strengthen-banner.svg,https://files.data.spotlightpa.org/uploads/01fv/qrpv/tote-banner.svg"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01fv/qq3v/tote-rectangle.svg"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
show-newsletter = true
show-sticky = true
sticky-image-caption = "Donate to Spotlight PA, Get an Exclusive Tote Bag"
sticky-image = "https://files.data.spotlightpa.org/uploads/01fv/qq42/tote-square.svg"
sticky-link = "/donate/"