banner-active = true
banner = "**LIVE CORONAVIRUS TRACKER:** The latest county-by-county cases, hospitalizations, and more"
banner-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
promo-type = "image"
promo-image-caption = "Support Spotlight PA's fearless accountability journalism."
promo-image-desktop = "https://files.data.spotlightpa.org/uploads/01fs/ds6e/strengthen-banner.svg"
promo-desktop-width = 728
promo-desktop-height = 90
promo-image-mobile = "https://files.data.spotlightpa.org/uploads/01fx/qbjx/democracy-rectangle-general.svg"
promo-mobile-width = 500
promo-mobile-height = 250
promo-link = "/donate/"
promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
show-newsletter = true
show-sticky = true
sticky-image-caption = "Support Spotlight PA's fearless accountability journalism."
sticky-image = "file:///Users/baxterc/Downloads/works_for_you_square.svg"
sticky-link = "/donate/"