promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
promo-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
banner = "We’re so close! We have to raise just $1,234 more TODAY to unlock a $10,000 matching gift. Help power tough accountability reporting on our state government. **Give now »**"
banner-link = "/donate/"
banner-active = false