promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
promo-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
banner = "**LET'S CELEBRATE:** For Spotlight PA's 1st birthday, give a gift to support investigative journalism."
banner-link = "/donate/"
banner-active = true