promo-text = "Map of latest Pa. coronavirus cases, county-by-county numbers"
promo-link = "/news/2020/03/pa-coronavirus-updates-cases-map-live-tracker/"
promo-active = true
banner = "**THE TRUTH MATTERS:** Now more than ever, our investigative journalism needs your support. Donate now."
banner-link = "/donate/"
banner-active = true